# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ybcJ8hb3Xycwda0RGSMdVM7wR7A308Db
"""

!pip install -q pandas scikit-learn matplotlib seaborn


import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import zipfile
import urllib.request
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score


zip_url = "https://archive.ics.uci.edu/ml/machine-learning-databases/00360/AirQualityUCI.zip"
zip_path = "AirQualityUCI.zip"
csv_filename = "AirQualityUCI.csv"

urllib.request.urlretrieve(zip_url, zip_path)

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extract(csv_filename)


df = pd.read_csv(csv_filename, sep=';', decimal=',', low_memory=False)
df = df.iloc[:, :-2]


df['Date_Time'] = pd.to_datetime(df['Date'] + ' ' + df['Time'], format="%d/%m/%Y %H.%M.%S", errors='coerce')
df.drop(columns=['Date', 'Time'], inplace=True)


df.columns = [c.strip().replace(" ", "_").replace("(", "").replace(")", "") for c in df.columns]


print("📋 Columns in dataset:")
print(df.columns.tolist())


df.replace(-200, np.nan, inplace=True)
df.dropna(inplace=True)


target = 'NO2GT'
features = df.columns.difference(['Date_Time', target])
X = df[features]
y = df[target]


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train, y_train)


y_pred = model.predict(X_test)


mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"\n✅ Mean Squared Error: {mse:.2f}")
print(f"✅ R² Score: {r2:.2f}")

plt.figure(figsize=(10, 5))
plt.scatter(y_test, y_pred, alpha=0.3)
plt.xlabel("Actual NO₂")
plt.ylabel("Predicted NO₂")
plt.title("Actual vs Predicted NO₂ Levels")
plt.grid(True)
plt.show()